config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, class_name: "Admin::Admin"
  devise_for :users

  root "homes#home"

  resources :users, only:[:index, :show, :edit, :update]
  resources :products, only:[:index, :show, :new, :create, :update, :destroy]
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/admin/admin.rb
class Admin::Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  attachment :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :products, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname, :tel, :postcode, :address])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def home
  end

  def about
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def new
    @product = Product.new
  end

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    
    
  end

  def create
    product = Product.new(product_params)
    product.user_id = current_user.id
    product.save
    redirect_to user_path(current_user.id)
  end

  private
  def product_params
    params.require(:product).permit(:image, :name, :explain, :price)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @products = current_user.products.all
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.update(user_params)
    redirect_to user_path
  end

  private
  def user_params
    params.require(:user).permit(:user_image, :name, :nickname, :email, :postcode, :address, :tel)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/home.html.erb
<h1>WEB直売所にようこそ</h1>

<h4>
  このサイトは売りたい生産者と新鮮な野菜を買いたい消費者を結ぶSNSです。
</h4>
<div><%= image_tag('img/weed.jpg', size: '1000x500') %></div>

app/views/products/edit.html.erb
<div class="container">
  <h3>投稿編集画面</h3>
  <dix class="row">

      <%= form_for(@product, url:products_path) do |f| %>
      <form class="form-horizontal" role="form">

        <div class="col-xs-4">
          <%= attachment_image_tag(@product, :image, size:'200x200', fallback: "no_image.jpg") %>
          <%= f.attachment_field :image %>
        </div>

        <div class="col-xs-8">
          <div class="row" style="margin-bottom: 20px;">
            <div class="col-xs-2">
              <%= f.label :name, '商品名', class: 'control-label' %>
            </div>
            <div class="col-xs-2">
              <%= f.text_field :name %>
            </div>
          </div>

          <div class="row" style="margin-bottom: 20px;">
            <div class="col-xs-2">
              <%= f.label :explain, '商品説明', class: 'control-label' %>
            </div>
            <div class="col-xs-2">
              <%= f.text_area :explain %>
            </div>
          </div>

          <div class="row" style="margin-bottom: 20px;">
            <div class="col-xs-2">
              <%= f.label :price, '価格', class: 'control-label' %>
            </div>
            <div class="col-xs-2">
              <%= f.text_field :price %>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-6">
              <%= f.submit '新規登録', class: "btn btn-primary pull-right"%>
            </div>
          </div>
        </div>

      </div>
    </form>
    <% end %>
    </div>
  </div>
</dix>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h4>ユーザー詳細</h4>
        
    </div>




    <div class="col-xs-6">
      <h4>投稿一覧</h4>
      <div class="row">

        <% @products.each do |product| %>
          <div class="col-xs-6 mx-auto">
            <div class="row">
              <%= link_to product_path(product.id) do %>
                <%= attachment_image_tag product, :image, fallback: "no_image.jpg", width: "90%", height: "auto", class: "text-center" %>
              <% end %>
            </div>

            <div class="row">
              <%= product.name %>
            </div>

            <div class="row">￥<%= product.price %></div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container">
  <h3>新規投稿</h3>
  <dix class="row">

      <%= form_for(@product, url:products_path) do |f| %>
      <form class="form-horizontal" role="form">

        <div class="col-xs-4">
          <%= attachment_image_tag(@product, :image, size:'200x200', fallback: "no_image.jpg") %>
          <%= f.attachment_field :image %>
        </div>

        <div class="col-xs-8">
          <div class="row" style="margin-bottom: 20px;">
            <div class="col-xs-2">
              <%= f.label :name, '商品名', class: 'control-label' %>
            </div>
            <div class="col-xs-2">
              <%= f.text_field :name %>
            </div>
          </div>

          <div class="row" style="margin-bottom: 20px;">
            <div class="col-xs-2">
              <%= f.label :explain, '商品説明', class: 'control-label' %>
            </div>
            <div class="col-xs-2">
              <%= f.text_area :explain %>
            </div>
          </div>

          <div class="row" style="margin-bottom: 20px;">
            <div class="col-xs-2">
              <%= f.label :price, '価格', class: 'control-label' %>
            </div>
            <div class="col-xs-2">
              <%= f.text_field :price %>
            </div>
          </div>

          <div class="row">
            <div class="col-xs-6">
              <%= f.submit '新規登録', class: "btn btn-primary pull-right"%>
            </div>
          </div>
        </div>

      </div>
    </form>
    <% end %>
    </div>
  </div>
</dix>

app/views/products/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h4>ジャンル一覧</h4>
    </div>

    <div class="col-xs-8 col-xs-offset-1">
      <h4>商品詳細</h4>
      <div class="row">
        <div class="col-xs-7">
          <%= attachment_image_tag @product, :image, fallback: "no_image.jpg", width: "100%", height: "auto" %>
        </div>

        <div class="col-xs-4">
          <div class="row">
            <h3><%= @product.name %></h3>
            <p><%= @product.explain %></p>
          </div>

          <div class="row">
            <h3>￥<%= @product.price %>円</h3>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">

  <div class="row">
    <div class="col-xs-4 col-xs-offset-1">
      <span style="display: block; margin-bottom: 30px; background-color: #cccccc; text-align: center;">
        <h3>登録情報編集</h3>
      </span>
    </div>
  </div>
</div>

<%= form_for(@user,url:users_path) do |f| %>
<div class="container">
  <div class="row">
    <div class="col-xs-12">

      <div class="form-group">
        <div class="field row">
          <%= f.label :name, "名前", class: "col-xs-3" %>
          <%= f.text_field :name, class: "col-xs-2" %>
        </div>
      </div>

      <div class="form-group">
        <div class="field row">
          <%= f.label :nickname, "ニックネーム", class: "col-xs-3" %>
          <%= f.text_field :nickname, class: "col-xs-2" %>
        </div>
      </div>

      <div class="form-group">
        <div class="field row">
          <%= f.label :email, "メールアドレス", class: "col-xs-3" %>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "col-xs-2" %>
        </div>
      </div>

      <div class="form-group">
        <div class="field row">
          <%= f.label :postcode, "郵便番号(ハイフンなし)", class: "col-xs-3" %>
          <%= f.text_field :postcode, class: "col-xs-2" %>
        </div>
      </div>

      <div class="form-group">
        <div class="field row">
          <%= f.label :address, "住所", class: "col-xs-3" %>
          <%= f.text_field :address, class: "col-xs-5" %>
        </div>
      </div>

      <div class="form-group">
        <div class="field row">
          <%= f.label :tel, "電話番号(ハイフンなし)", class: "col-xs-3" %>
          <%= f.text_field :tel, class: "col-xs-2" %>
        </div>
      </div>

      <div class="row", style="margin-top: 50px;">
        <div class="col-xs-6" style="display: flex; justify-content: space-between;">
            <%= f.submit '編集内容を保存する', class: "btn btn-primary"%>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <h4>ユーザー詳細</h4>
        <%= attachment_image_tag @user, :user_image, format: 'jpeg', fallback: "no_image.jpg", width: "100%", heigth: "auto" %>
        <table class="table">
          <thead>
            <tr>
              <th>表示名</th>
              <th><%= @user.nickname %></th>
            </tr>
            <tr>
              <th>紹介</th>
              <th></th>
            </tr>
            <tr>
              <th>フォロー中</th>
              <th></th>
            </tr>
            <tr>
              <th>フォロワー</th>
              <th></th>
            </tr>
          </thead>
        </table>
      <%= link_to "ユーザー情報編集", edit_user_path %>

      <%= link_to "新規投稿", new_product_path %>
    </div>




    <div class="col-xs-6">
      <h4>投稿一覧</h4>
      <div class="row">

        <% @products.each do |product| %>
          <div class="col-xs-6 mx-auto">
            <div class="row">
              <%= link_to product_path(product.id) do %>
                <%= attachment_image_tag product, :image, fallback: "no_image.jpg", width: "90%", height: "auto", class: "text-center" %>
              <% end %>
            </div>

            <div class="row">
              <%= product.name %>
            </div>

            <div class="row">￥<%= product.price %></div>
          </div>
        <% end %>

      </div>
    </div>
  </div>
</div>